CREATE DATABASE node_mysql_ts;

CREATE TABLE posts(
  id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR/* (255) */ NOT NULL,
  description TEXT NOT NULL,
  image_url TEXT NULL,
  createat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DESCRIBE posts;